### ISSUE TITLE
error loading the lib via gradle

### ISSUE THREAD

**Issue by neXus1987** [beaconinside/android-sdk#1]
Hi all,

i have added following to the build file:
   maven {
            url "https://maven.beaconinside.com"
        }

and following to the app file:
 implementation 'com.beaconinside:proximity-sdk:3.0.1'

and get e.g. following error (also for the other productFlavors):
Unable to resolve dependency for ':app@XXXXXXXXXXDebug/compileClasspath': Could not resolve com.beaconinside:proximity-sdk:3.0.1.
Open File
Show Details

do you have an idea?

thanks
Phil

**Comment by bashtian** [comment]
Hi Phil,
please make sure that the repository is in the right place the project build.gradle (not the app build.gradle)
```
allprojects {
	repositories {
		...
	}
}
````
Please let me know if this solves your problem.

**Comment by neXus1987** [comment]
Hi Bashtian,
yes it is:


allprojects {
    repositories {
        jcenter()
        mavenCentral()
        google()
        maven {
            url "https://maven.beaconinside.com"
        }
 
        maven {
            url 'https://download.01.org/crosswalk/releases/crosswalk/android/maven2'
        }
        maven {
            url "https://maven.google.com"
        }

    }
}

**Comment by bashtian** [comment]
This seems to be a configuration or network issue. 

Can you access this file https://maven.beaconinside.com/com/beaconinside/proximity-sdk/3.0.1/proximity-sdk-3.0.1.aar ?
Can you try to create a new project and see if this works?

**Comment by neXus1987** [comment]
i have setup a new project, i attach both files. Still the same error. I can access this file via Browser. I have also clean the buildcache from gradle.

[build_app.txt](https://github.com/beaconinside/android-sdk/files/2282877/build_app.txt)
[build_project.txt](https://github.com/beaconinside/android-sdk/files/2282878/build_project.txt)


Errors:

Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.beaconinside:proximity-sdk:3.0.1.
Open File
Show Details


Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not resolve com.beaconinside:proximity-sdk:3.0.1.
Open File
Show Details


Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Could not resolve com.beaconinside:proximity-sdk:3.0.1.
Open File
Show Details


Unable to resolve dependency for ':app@release/compileClasspath': Could not resolve com.beaconinside:proximity-sdk:3.0.1.
Open File
Show Details


Unable to resolve dependency for ':app@releaseUnitTest/compileClasspath': Could not resolve com.beaconinside:proximity-sdk:3.0.1.
Open File
Show Details

**Comment by bashtian** [comment]
The Gradle files look fine, can you please try if  https://stackoverflow.com/a/47833606 works?

**Comment by neXus1987** [comment]
The offline was already unchecked and i got still the same error.

**Comment by bashtian** [comment]
Unfortunately I'm not able to reproduce this problem, I used the same gradle files that you uploaded. Maybe it's some caching or proxy problem.

You also can use the AAR linked above directly. You can add it in Android Studio under "New Module" and then "Import .JAR/.AAR Package"

You also need to add following dependencies to your apps build.gradle file:

```
    implementation 'com.google.protobuf.nano:protobuf-javanano:3.1.0'
    implementation 'com.google.android.gms:play-services-nearby:15.0.1'
    implementation 'com.google.android.gms:play-services-location:15.0.1'
    implementation 'com.google.android.gms:play-services-places:15.0.1'
````

**Comment by neXus1987** [comment]
ok this could be a good fallback. As i see gradle tries to download following file:
https://maven.beaconinside.com/com/beaconinside/proximity-sdk/3.0.1/proximity-sdk-3.0.1.pom

does this make sense, i think this file doesn´t exist?!

**Comment by neXus1987** [comment]
With a newer Java JDK it will work :)  Thanks!

**Comment by bashtian** [comment]
Good to know that Java has some problems with the SSL certificates, thank you for tracking this problem down.
